import sys

# 将plink输出的距离矩阵转换为MEGA适用的meg格式
# 必须是下三角无对角线矩阵（--triangel）

dist_input=sys.argv[1]
sample_input=sys.argv[2]

meg_output=dist_input+".meg"

# 读取样本列表
samples=[]
with open(sample_input) as f:
    for i in f:
        samples.append(i.rstrip().split()[1])

with open(dist_input) as src, open(meg_output, "w") as dst:
    # 文件头
    dst.write("#mega\n")
    dst.write("!Title: distance matrix generated by Plink;\n")
    dst.write(f"!Format DataType=Distance DataFormat=LowerLeft NTaxa={len(samples)};\n")

    # 样品名
    for i in samples:
        dst.write(f"#{i}\n")
    
    dst.write("\n")

    for i in src:
        dst.write(i)




